"""Update constraints and final score

Revision ID: 286436014749
Revises: d2de3f82d171
Create Date: 2025-12-31 22:39:12.213693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '286436014749'
down_revision = 'd2de3f82d171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['candidat_id'])

    with op.batch_alter_table('eligibilites', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_eligibilite', ['type_diplome_requis', 'branche_source', 'filiere_id'])

    with op.batch_alter_table('evaluateurs', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['user_id'])

    with op.batch_alter_table('final_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidat_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('note_ai', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('note_jury', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['candidat_id'])
        batch_op.drop_constraint(batch_op.f('final_scores_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('final_scores_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'candidats', ['candidat_id'], ['id'])
        batch_op.drop_column('note_evaluateur_id')
        batch_op.drop_column('score_ai_id')

    with op.batch_alter_table('note_evaluateur', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_eval', ['evaluateur_id', 'candidat_id'])

    with op.batch_alter_table('score_ai', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['candidat_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_num',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_num',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('score_ai', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('note_evaluateur', schema=None) as batch_op:
        batch_op.drop_constraint('unique_eval', type_='unique')

    with op.batch_alter_table('final_scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_ai_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('note_evaluateur_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('final_scores_ibfk_2'), 'score_ai', ['score_ai_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('final_scores_ibfk_1'), 'note_evaluateur', ['note_evaluateur_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('created_at')
        batch_op.drop_column('note_jury')
        batch_op.drop_column('note_ai')
        batch_op.drop_column('candidat_id')

    with op.batch_alter_table('evaluateurs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('eligibilites', schema=None) as batch_op:
        batch_op.drop_constraint('unique_eligibilite', type_='unique')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('candidats', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
