"""Ajout de rn_diplome à la table Documents

Revision ID: 4679bed408d5
Revises: ab43f31fb03c
Create Date: 2025-12-26 15:51:16.730191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4679bed408d5'
down_revision = 'ab43f31fb03c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidats', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['cne'])

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rn_diplome', sa.String(length=255), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['phone_num'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('rn_diplome')

    with op.batch_alter_table('candidats', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
