"""Initialisation complète des modèles

Revision ID: ab43f31fb03c
Revises: 
Create Date: 2025-12-19 17:20:35.759527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab43f31fb03c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filieres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_filiere', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom_filiere')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('eligibilites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_diplome_requis', sa.String(length=50), nullable=False),
    sa.Column('branche_source', sa.String(length=100), nullable=False),
    sa.Column('filiere_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['filiere_id'], ['filieres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('prenom', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('cin', sa.String(length=50), nullable=False),
    sa.Column('phone_num', sa.String(length=20), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cin'),
    sa.UniqueConstraint('email')
    )
    op.create_table('candidats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cne', sa.String(length=50), nullable=False),
    sa.Column('t_diplome', sa.String(length=50), nullable=True),
    sa.Column('branche_diplome', sa.String(length=100), nullable=True),
    sa.Column('bac_type', sa.String(length=50), nullable=True),
    sa.Column('moy_bac', sa.Float(), nullable=True),
    sa.Column('m_s1', sa.Float(), nullable=True),
    sa.Column('m_s2', sa.Float(), nullable=True),
    sa.Column('m_s3', sa.Float(), nullable=True),
    sa.Column('m_s4', sa.Float(), nullable=True),
    sa.Column('filiere_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['filiere_id'], ['filieres.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('formule', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bac', sa.String(length=255), nullable=True),
    sa.Column('rn_bac', sa.String(length=255), nullable=True),
    sa.Column('diplome', sa.String(length=255), nullable=True),
    sa.Column('cin_file', sa.String(length=255), nullable=True),
    sa.Column('candidat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidat_id'], ['candidats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note_evaluateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_eval', sa.Float(), nullable=False),
    sa.Column('evaluateur_id', sa.Integer(), nullable=False),
    sa.Column('candidat_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidat_id'], ['candidats.id'], ),
    sa.ForeignKeyConstraint(['evaluateur_id'], ['evaluateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_ai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidat_id', sa.Integer(), nullable=False),
    sa.Column('note_ai', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['candidat_id'], ['candidats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('final_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_evaluateur_id', sa.Integer(), nullable=False),
    sa.Column('score_ai_id', sa.Integer(), nullable=False),
    sa.Column('note_final', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['note_evaluateur_id'], ['note_evaluateur.id'], ),
    sa.ForeignKeyConstraint(['score_ai_id'], ['score_ai.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('final_scores')
    op.drop_table('score_ai')
    op.drop_table('note_evaluateur')
    op.drop_table('documents')
    op.drop_table('evaluateurs')
    op.drop_table('candidats')
    op.drop_table('users')
    op.drop_table('eligibilites')
    op.drop_table('roles')
    op.drop_table('filieres')
    # ### end Alembic commands ###
